// smbclient-sys (rust bindings for libsmbclient from Samba project)
// Copyright (c) 2016 Konstantin Gribov
//
// This file is part of smbclient-sys.
//
// smbclient-sys is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// smbclient-sys is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with smbclient-sys.  If not, see <http://www.gnu.org/licenses/>.

//! `smbclient-sys` is bindings for `libsmbclient` from [Samba](https://www.samba.org) project
//!
//! Bindings are autogenerated with rust-bindgen from `libsmbclient.h`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(missing_docs)]

extern crate libc;

pub const SMBC_FALSE: smbc_bool = 0;
pub const SMBC_TRUE: smbc_bool = 1;

include!(concat!(env!("OUT_DIR"), "/libsmbclient.rs"));
